apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-device-plugin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubernetes-gpu.metaLabels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "kubernetes-gpu.metaLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-gpu.metaLabels" . | nindent 8 }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccount: nvidia-gpu-device-plugin
      serviceAccountName: nvidia-gpu-device-plugin
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      priorityClassName: system-node-critical
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      containers:
      - image: {{ .Values.device.image.repository }}:{{ .Values.device.image.tag }}
        command: ["/usr/bin/nvidia-gpu-device-plugin", "-logtostderr"]
        name: nvidia-gpu-device-plugin
{{- if .Values.device.resources }}
        resources:
{{ toYaml .Values.device.resources | indent 10 }}
{{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
