apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubernetes-gpu.metaLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubernetes-gpu.metaLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-gpu.metaLabels" . | nindent 8 }}
    spec:
      serviceAccount: nvidia-driver-installer
      serviceAccountName: nvidia-driver-installer
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
      hostNetwork: true
      hostPID: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: nvidia-install-dir-host
        hostPath:
          path: /opt/nvidia
      - name: root-mount
        hostPath:
          path: /
      initContainers:
      - image: {{ .Values.driver.image.repository }}:{{ .Values.driver.image.tag }}
        imagePullPolicy: Always
        name: nvidia-driver-installer
{{- if .Values.driver.resources }}
        resources:
{{ toYaml .Values.driver.resources | indent 10 }}
{{- end }}
        securityContext:
          privileged: true
        env:
          - name: NVIDIA_INSTALL_DIR_HOST
            value: /opt/nvidia
          - name: NVIDIA_INSTALL_DIR_CONTAINER
            value: /usr/local/nvidia
          - name: ROOT_MOUNT_DIR
            value: /root
        volumeMounts:
        - name: nvidia-install-dir-host
          mountPath: /usr/local/nvidia
        - name: dev
          mountPath: /dev
        - name: root-mount
          mountPath: /root
      containers:
      - image: gcr.io/google-containers/pause:2.0
        name: pause
