apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-driver-installer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubernetes-gpu.metaLabels" . | nindent 4 }}
rules:
- apiGroups:      ['policy','extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  ['privileged']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-driver-installer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubernetes-gpu.metaLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-driver-installer
subjects:
- kind: ServiceAccount
  name: nvidia-driver-installer
  namespace: {{ .Values.namespace }}
