namespace: kube-system

# Adding Capability to Add Custom Toleration to GPU Device and Driver Pods
# This is global to both Device and Driver as we intend to run this on the same node
tolerations:
- key: "node.kubernetes.io/master"
  effect: "NoSchedule"
  operator: "Exists"

# Adding Capability to Add Custom Node Selector to GPU Device and Driver Pods
# This is global to both Device and Driver as we intend to run this on the same node
nodeSelector: {}

driver:
  image:
    repository: quay.io/giantswarm/coreos-nvidia-driver-installer
    tag: 440.82.02
  resources:
    requests:
      cpu: 0.15
device:
  image:
    repository: quay.io/giantswarm/nvidia-gpu-device-plugin
    tag: 1.0.0
  resources:
    requests:
      cpu: 50m
      memory: 10Mi
      
